### ISSUE TITLE
Name of the extension.

### ISSUE THREAD

**Issue by phcerdan** [KitwareMedical/SlicerSkeletalRepresentation#1]
[Slicer guidelines](https://www.slicer.org/wiki/Documentation/Nightly/Developers/FAQ/Extensions#Should_the_name_of_the_source_repository_match_the_name_of_the_extension_.3F) suggests if the name of the extension is XXX, the github repository should be called SlicerExtension_XXX or similar.

Beyond this, I am concern about the name. Is SRep the best name for non-expert users? 

Would be SkeletalRepresentation better? @bpaniagua @vicory

**Comment by bpaniagua** [comment]
Lets see what @vicory 's opinion is. I think S-rep in our specific community (shape modeling researchers) should be good enough. We can always add information in the tutorial and in the help of the module.

**Comment by phcerdan** [comment]
Pinging @vicory

**Comment by vicory** [comment]
I have no strong feelings one way or the other about the repository name, but if we want to be consistent we'd need to rename other extensions like https://github.com/KitwareMedical/ShapeRegressionExtension.

As for the SRep abbreviation issue, I think its fine for the repo name. We could always use the long names in the actual Slicer modules (i.e. Skeletal Model Visualization) and/or have them in a separate Skeletal Models module category to make things clear and non-expert users will probably never see the actual github repo name anyway.

**Comment by ZhiyLiu** [comment]
Yes. As a developer, either name works for me. Let's meet the requirement of standard Slicer extension. I will submit Extension Index as soon as @phcerdan rename this repository. Thanks.

**Comment by phcerdan** [comment]
I don't have the admin rights to change the name, we will need superpowers from @bpaniagua to change it to SlicerSkeletalRepresentation.

**Comment by vicory** [comment]
Name is changed to SlicerSkeletalRepresentation.
