### ISSUE TITLE
Homepage of this extension

### ISSUE THREAD

**Issue by ZhiyLiu** [KitwareMedical/SlicerSkeletalRepresentation#12]
Need access to edit the home page and a place to upload the tutorial.

**Comment by ZhiyLiu** [comment]
I guess home page should be:
http://slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/SkeletalRepresentation

**Comment by ZhiyLiu** [comment]
Wiki page http://slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/SkeletalRepresentation
has been set up. @phcerdan

**Comment by phcerdan** [comment]
Great @ZhiyLiu!
