### ISSUE TITLE
Use relative path and customize file names for s-reps

### ISSUE THREAD

**Issue by yehan0223** [KitwareMedical/SlicerSkeletalRepresentation#45]
The current way of saving s-reps uses absolute paths in header.xml, which can cause issue during the exchange of s-rep files between different machines.

Also, the current saving operation uses same file names (header.xml, up.vtp, down.vtp and crest.vtp) for all models, meaning that no more than one s-rep can be saved in the same folder. It may be better to rename the files with their original model names (hippocampus0_header.xml, hippocampus0_up.vtp, etc.). Multiple s-reps can then be stored under the same folder, instead of creating a separate folder for each of the s-reps.

What do you think? @bpaniagua @vicory

**Comment by bpaniagua** [comment]
@yehan0223 
Thanks for reporting this problem. I think your proposed solution makes sense, please go ahead and work on making this change.


Bea

**Comment by Connor-Bowley** [comment]
This issue is to be overcome by events with the new SRep work being done that will be merged into this repo

**Comment by Connor-Bowley** [comment]
This issue has been overcome by events with the new SRep work being done that was merged into this repo.
